/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6PVui9uTyFt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from '@/components/ui/card'

function Leaderboard() {
  return (
    <>
      <Card className="w-full max-w-3xl">
        <CardHeader className="flex flex-col items-center gap-2 border-b pb-4">
          <CardTitle className="text-2xl font-bold">Leaderboard</CardTitle>
          <CardDescription className="text-muted-foreground">
            Top 10 high scores
          </CardDescription>
        </CardHeader>
        <CardContent className="py-4">
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              1
            </div>
            <div className="space-y-1">
              <div className="font-medium">John Doe</div>
              <div className="text-muted-foreground text-xs">
                August 4, 2024
              </div>
            </div>
            <div className="text-right font-medium">1234</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              2
            </div>
            <div className="space-y-1">
              <div className="font-medium">Jane Smith</div>
              <div className="text-muted-foreground text-xs">
                August 3, 2024
              </div>
            </div>
            <div className="text-right font-medium">1200</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              3
            </div>
            <div className="space-y-1">
              <div className="font-medium">Bob Johnson</div>
              <div className="text-muted-foreground text-xs">
                August 2, 2024
              </div>
            </div>
            <div className="text-right font-medium">1150</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              4
            </div>
            <div className="space-y-1">
              <div className="font-medium">Sarah Lee</div>
              <div className="text-muted-foreground text-xs">
                August 1, 2024
              </div>
            </div>
            <div className="text-right font-medium">1100</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              5
            </div>
            <div className="space-y-1">
              <div className="font-medium">Tom Wilson</div>
              <div className="text-muted-foreground text-xs">July 31, 2024</div>
            </div>
            <div className="text-right font-medium">1050</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              6
            </div>
            <div className="space-y-1">
              <div className="font-medium">Emily Davis</div>
              <div className="text-muted-foreground text-xs">July 30, 2024</div>
            </div>
            <div className="text-right font-medium">1000</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              7
            </div>
            <div className="space-y-1">
              <div className="font-medium">Michael Brown</div>
              <div className="text-muted-foreground text-xs">July 29, 2024</div>
            </div>
            <div className="text-right font-medium">950</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              8
            </div>
            <div className="space-y-1">
              <div className="font-medium">Jessica Thompson</div>
              <div className="text-muted-foreground text-xs">July 28, 2024</div>
            </div>
            <div className="text-right font-medium">900</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              9
            </div>
            <div className="space-y-1">
              <div className="font-medium">David Anderson</div>
              <div className="text-muted-foreground text-xs">July 27, 2024</div>
            </div>
            <div className="text-right font-medium">850</div>
          </div>
          <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b py-3 last:border-b-0">
            <div className="bg-primary text-primary-foreground flex h-8 w-8 items-center justify-center rounded-full">
              10
            </div>
            <div className="space-y-1">
              <div className="font-medium">Olivia Martinez</div>
              <div className="text-muted-foreground text-xs">July 26, 2024</div>
            </div>
            <div className="text-right font-medium">800</div>
          </div>
        </CardContent>
      </Card>
    </>
  )
}

export default Leaderboard
